<template>
  <iframe
    allowfullscreen
    id="ytplayer"
    type="text/html"
    width="640"
    height="360"
    src="https://www.youtube.com/embed/LEl60NRhknE?autoplay=1&origin=http://example.com"
    frameborder="0"
    modestbranding
  ></iframe>
</template>
